addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.6.3")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.6.3")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.6.4")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.11.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.4.6")
